spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/car_rental
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  mvc:
    format:
      date: yyyy-MM-dd
  thymeleaf:
    cache: false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.carrental.entity